name: build
on:
  push:
    branches:
      - main
      
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: git.bitstorm.ca # e.g., docker.io for Docker Hub
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: git.bitstorm.ca/global_dynamics/sapho:latest

